# Generated by Django 5.2 on 2025-05-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_classif', models.CharField(max_length=100)),
                ('award_title', models.CharField(max_length=100)),
                ('award_desc', models.CharField(max_length=200)),
                ('award_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Enter your name', max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=3)),
                ('birth_date', models.DateField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('user_title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('start_date', models.DateField(max_length=20)),
                ('finish_date', models.DateField(max_length=20)),
                ('project_status', models.CharField(max_length=50)),
            ],
        ),
    ]
