# Generated by Django 5.2 on 2025-05-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_desc',
            field=models.CharField(blank=True, default='No description provided', max_length=100),
        ),
    ]
