# Generated by Django 5.2 on 2025-05-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdetails',
            name='profile_avatar_id',
            field=models.IntegerField(default=1),
        ),
    ]
