# Generated by Django 5.2 on 2025-05-14 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_personalinformation_signup_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='signup_details',
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.CharField(default='John Doe', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.project')),
            ],
        ),
    ]
