# Generated by Django 5.2 on 2025-05-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250522_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='signupdetails',
            name='department',
            field=models.CharField(default='No department yet', max_length=100),
        ),
        migrations.AlterField(
            model_name='signupdetails',
            name='position',
            field=models.CharField(default='No position yet', max_length=100),
        ),
    ]
