# Generated by Django 5.2 on 2025-05-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250523_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdetails',
            name='department',
            field=models.CharField(default='No position yet', max_length=100),
        ),
        migrations.AlterField(
            model_name='signupdetails',
            name='position',
            field=models.CharField(default='No position yet', max_length=100),
        ),
    ]
