# Generated by Django 5.2 on 2025-05-22 XX:XX

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_project_id_alter_signupdetails_department_and_more'),  # Replace with your actual previous migration
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS core_project;"
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project_desc', models.CharField(max_length=100, blank=True, default='No description provided')),
                ('project_id', models.CharField(max_length=20, unique=True, blank=True)),
                ('start_date', models.DateField(max_length=20)),
                ('finish_date', models.DateField(max_length=20)),
                ('project_status', models.CharField(max_length=50)),
                ('project_manager', models.CharField(max_length=100)),
            ],
        ),
    ]