# Generated by Django 5.2 on 2025-05-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_personalinformation_signup_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_desc',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
