# Generated by Django 5.2 on 2025-05-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_drivefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_avatar', models.ImageField(upload_to='avatars/')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('complete_address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='drivefile',
            name='file_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
