# Generated by Django 5.2 on 2025-05-25 08:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_signupdetails_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signupdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='signupdetails',
            name='user_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='signupdetails',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='signupdetails',
            name='complete_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='signupdetails',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='signupdetails',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='signupdetails',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='signupdetails',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='signupdetails',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='signupdetails',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='signupdetails',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
