# Generated by Django 5.2 on 2025-05-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_project_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_desc',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
