# Generated by Django 5.2 on 2025-05-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_signupdetails_created_at_signupdetails_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivefile',
            name='uploader_department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='drivefile',
            name='uploader_user_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='drivefolder',
            name='creator_department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='drivefolder',
            name='creator_user_level',
            field=models.IntegerField(default=1),
        ),
    ]
