# Generated by Django 5.2 on 2025-05-12 15:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_signupdetails_alter_drivefile_file_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('posted_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='signup_details',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='personal_information', to='core.signupdetails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='birth_date',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
    ]
