# Generated by Django 5.2 on 2025-05-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250522_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdetails',
            name='department',
            field=models.CharField(default='No position yet', max_length=100),
        ),
    ]
