# Generated by Django 5.2 on 2025-05-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_signupdetails_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupdetails',
            name='profile_avatar',
        ),
        migrations.AddField(
            model_name='signupdetails',
            name='profile_avatar_id',
            field=models.CharField(default=1, max_length=2),
        ),
    ]
