# Generated by Django 5.2 on 2025-05-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_drivefile_uploader_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
