# Generated by Django 5.2 on 2025-05-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_signupdetails_profile_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupdetails',
            name='profile_avatar_id',
        ),
        migrations.AddField(
            model_name='signupdetails',
            name='profile_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
