# Generated by Django 5.2 on 2025-05-12 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_personalinformation_signup_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='signup_details',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_information', to='core.signupdetails'),
        ),
    ]
