# Generated by Django 5.2 on 2025-05-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_signupdetails_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupdetails',
            name='age',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
