# Generated by Django 5.2 on 2025-05-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_signupdetails_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='department',
            field=models.CharField(default='IT', max_length=50),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='position',
            field=models.CharField(default='Employee', max_length=50),
        ),
        migrations.AddField(
            model_name='signupdetails',
            name='department',
            field=models.CharField(default='IT', max_length=50),
        ),
        migrations.AddField(
            model_name='signupdetails',
            name='position',
            field=models.CharField(default='Employee', max_length=50),
        ),
    ]
