# Generated by Django 5.2 on 2025-05-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_signupdetails_profile_avatar_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupdetails',
            name='profile_avatar',
        ),
        migrations.AddField(
            model_name='signupdetails',
            name='profile_avatar_id',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
