# Generated by Django 5.2 on 2025-05-13 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification'),
        ('core', '0007_alter_personalinformation_signup_details'),
    ]

    operations = [
    ]
