# Generated by Django 5.2 on 2025-05-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_personalinformation_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdetails',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='signupdetails',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
