# Generated by Django 5.2 on 2025-05-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editprofile',
            name='new_address',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
