# Generated by Django 5.2 on 2025-05-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_editprofile_new_address_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editprofile',
            name='new_address',
            field=models.CharField(default=None),
        ),
    ]
