# Generated by Django 5.2 on 2025-05-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_editprofile_new_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editprofile',
            name='new_address',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
